
// SEARCH
export const GET_SEARCH_TERMS_INITIATE =    'GET_SEARCH_TERMS_INITIATE';
export const GET_SEARCH_TERMS_SUCCESS =     'GET_SEARCH_TERMS_INITIATE';
export const GET_SEARCH_TERMS_FAIL =        'GET_SEARCH_TERMS_INITIATE';

export const GET_STATS_INITIATE =   'GET_STATS_INITIATE';
export const GET_STATS_SUCCESS =    'GET_STATS_SUCCESS';
export const GET_STATS_FAIL =       'GET_STATS_FAIL';

export const GET_VIDEOS_INITIATE =     'GET_VIDEOS_INITIATE';
export const GET_VIDEOS_SUCCESS =      'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAIL =         'GET_VIDEOS_FAIL';

//SAVE FAVOURITE
export const SAVE_VIDEO_INITIATE =  'SAVE_VIDEO_INITIATE';
export const SAVE_VIDEO_SUCCESS =   'SAVE_VIDEO_SUCCESS';
export const SAVE_VIDEO_FAIL =      'SAVE_VIDEO_FAIL';

// LOAD FAVOURITES
export const LOAD_SAVED_INITIATE =  'LOAD_SAVED_INITIATE';
export const LOAD_SAVED_SUCCESS =   'LOAD_SAVED_SUCCESS';
export const LOAD_SAVED_FAIL =      'LOAD_SAVED_FAIL';

