export const YoutubAPIKey = "Get your own key. Put it here"

export const categories = [
    "Film & Animation",
    "Autos & Vehicles",
    "Music", "Pets & Animals",
    "Sports",
    "Short Movies",
    "Travel & Events",
    "Gaming",
    "Videoblogging",
    "People & Blogs",
    "Comedy",
    "Entertainment",
    "News & Politics",
    "Howto & Style",
    "Education",
    "Science & Technology",
    "Movies",
    "Anime/Animation",
    "Action/Adventure",
    "Classics",
    "Comedy",
    "Documentary",
    "Drama",
    "Family",
    "Foreign",
    "Horror",
    "Sci-Fi/Fantasy",
    "Thriller",
    "Shorts",
    "Shows",
    "Trailers",
];

export const categoriesWithIds = [
    { ID: 1,     Category: "Film & Animation" },
    { ID: 2,     Category: "Autos & Vehicles" },
    { ID: 10,    Category: "Music" },
    { ID: 15,    Category: "Pets & Animals" },
    { ID: 17,    Category: "Sports" },
    { ID: 18,    Category: "Short Movies" },
    { ID: 19,    Category: "Travel & Events" },
    { ID: 20,    Category: "Gaming" },
    { ID: 21,    Category: "Videoblogging" },
    { ID: 22,    Category: "People & Blogs" },
    { ID: 23,    Category: "Comedy" },
    { ID: 24,    Category: "Entertainment" },
    { ID: 25,    Category: "News & Politics" },
    { ID: 26,    Category: "Howto & Style" },
    { ID: 27,    Category: "Education" },
    { ID: 28,    Category: "Science & Technology" },
    { ID: 30,    Category: "Movies"},
    { ID: 31,    Category: "Anime/Animation"},
    { ID: 32,    Category: "Action/Adventure"},
    { ID: 33,    Category: "Classics"},
    { ID: 34,    Category: "Comedy"},
    { ID: 35,    Category: "Documentary"},
    { ID: 36,    Category: "Drama"},
    { ID: 37,    Category: "Family"},
    { ID: 38,    Category: "Foreign"},
    { ID: 39,    Category: "Horror"},
    { ID: 40,    Category: "Sci-Fi/Fantasy"},
    { ID: 41,    Category: "Thriller"},
    { ID: 42,    Category: "Shorts"},
    { ID: 43,    Category: "Shows"},
    { ID: 44,    Category: "Trailers"},
];