export const videoStyles = {
    pageContainer: {
        fontFamily: 'Roboto,arial,sans-serif',
        backgroundColor: 'background-color: rgba(193, 193, 193, 0.22)'
    },
    // for phones/tablets
    contentMedia: {
        // width: '438px',
        position: 'relative',
        top: '10px',
        maxWidth: 'none',
        minWidth: '0',
            marginLeft: 'auto',
        marginRight: 'auto',
        boxSizing: 'border-box',
    },
    content: {
        position: 'relative',
        top: '10px',
        maxWidth: 'none',
        minWidth: '0',
        marginLeft: 'auto',
        marginRight: 'auto',
        // width: '1003px',
        boxSizing: 'border-box',
    },
    colContainer: {
        display: 'table',
        tableLayout: 'fixed',
        // width: '100%',
        boxSizing: 'border-box',
    },
    colContainerInner: {
        display: 'table-row',
    },
    primaryColumn: {
        display: 'table-cell',
        verticalAlign: 'top',
        margin: '0 0 10px',
        border: '0',
        background: '#fff',
        boxShadow: '0 1px 2px rgba(0,0,0,.1)',
        boxSizing: 'border-box',
    },
    sectionList: {
        margin: '0',
        padding: '0',
        border: '0',
        fontSize: '100%',
        background: 'transparent',
    },
    itemSection: {
        listStyle: 'none',
    },
    videoItemsContainer: {
        borderBottom: '1px solid #e2e2e2',
        padding: '18px',
        position: 'relative',
        margin: '0',
        fontSize: '100%',
        background: 'transparent',
        display: 'block',
    },
    videoGrid: {
        display: 'block',
        position: 'relative',
        marginBottom: '-12px',
        marginRight: '-8px',
        listStyle: 'none',

    },
    videoList: {
        display: 'inline-block',
        marginRight: '10px',
        verticalAlign: 'top',
        // width: '540px',
        wordWrap: 'break-word',
        marginBottom: '12px',
        // columnCount: '2',
        // columnWidth: '196px',
    },
    videoListItem: {
        display: 'block',
        fontSize: '11px',
        color: '#767676',
        lineHeight: '1.3em',
        position: 'relative',
        margin: '0',
        padding: '15px', //'0 0 30px 0',
        // width: '100%',
        // height: '100%',
        border: '0',
        background: 'transparent',
        wordWrap: 'break-word',
    },
    thumbnailContainer: {
        marginBottom: '4px',
        display: 'block',
        position: 'relative',
        // height: '100%',
        overflow: 'hidden',
        lineHeight: '0',
    },
    thumbnail: {
        position: 'relative',
        overflow: 'hidden',
        background: '#f1f1f1',
        fontSize: '0',
        verticalAlign: 'middle',
        display: 'inline-block',
    },
    thumbnailSimple: {
        fontSize: '13px',
        outline: 'none'
    },
    detailsContainer: {
        overflow: 'hidden',
        position: 'relative',
        display: 'block',
        minWidth: '300px',
    },
    title: {
        marginRight: '20px',
        fontSize: '13px',
        marginBottom: '1px',
        maxWidth: '196px',
        fontWeight: '500',
        color: '#167ac6',
        maxHeight: '2.6em',
        backgroundColor: '#fff',
        display: 'block',
        lineHeight: '1.3em',
        overflow: 'hidden',
        position: 'relative',
        textOverflow: 'ellipsis',
        whiteSpace: 'normal',
        wordWrap: 'break-word',
    },
    videoMetaContainer: {
        display: 'block',
        margin: '0',
    },
    videoMetaList: {
        margin: '0',
        padding: '0',
        border: '0',
        fontSize: '100%',
        background: 'transparent',
        listStyle: 'none',
        color: '#767676',
        lineHeight: '1.3em',
    },
    videoMetaListItem: {
        lineHeight: '1.3em',
        display: 'inline-block',
        margin: '0',
        paddingRight: '20px',
        border: '0',
        fontSize: '100%',
        background: 'transparent',
        verticalAlign: 'top',
    },
    videoSaveButtonContainer: {
        lineHeight: '1.3em',
        display: 'inline-block',
        marginLeft: '-11px',
        paddingRight: '-12px',
        border: '0px',
        fontSize: '100%',
        background: 'transparent',
        verticalAlign: 'top',
    }
};